# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
#' @importFrom Rcpp sourceCpp
#' @rawNamespace useDynLib(redPATH)

calc_vec <- function(v1, v2) {
    .Call('_redPATH_calc_vec', PACKAGE = 'redPATH', v1, v2)
}

#' @export
KL <- function(x, logx) {
    .Call('_redPATH_KL', PACKAGE = 'redPATH', x, logx)
}

#' @export
ED2 <- function(x) {
    .Call('_redPATH_ED2', PACKAGE = 'redPATH', x)
}

